# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
                ('image', models.ImageField(upload_to='static/imagenes/')),
                ('archivo', models.FileField(upload_to='static/imagenes/')),
            ],
        ),
    ]
