# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='archivo',
            field=models.FileField(upload_to='static/archivos/'),
        ),
    ]
